### ISSUE TITLE
テストの実行結果の履歴を確認したい

### ISSUE THREAD

**Issue by takashi-moriya** [ihgs/tdd_exercise#7]
TDDのサイクルが回っているか確認するため、テストの実行結果の履歴を確認したい

**Comment by ihgs** [comment]
最大１０件まで表示。１０件以上は今後実装予定の詳細ダイアログで実装予定

マウスのカーソルを合わせると、実行時刻 HH:MM:SS 形式でツールチップを表示

<img width="282" alt="image" src="https://github.com/user-attachments/assets/e5e95d28-c490-45f8-9525-659d480f1aa9" />
